version: '3'
services:
  mysql-syslibrary:
    container_name: mysql-syslibrary
    command: '--default-authentication-plugin=mysql_native_password'
    image: 'mariadb:10'
    restart: always
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    networks:
      - app-connect
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - './database/init:/docker-entrypoint-initdb.d'
      - '../data/mysql:/var/lib/mysql'
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s
networks:
  app-connect:
    driver: bridge
